
<section class="flex items-center justify-center h-screen bg-gray-100">
    <div class="bg-white rounded-lg shadow-lg p-6 w-full max-w-md font-quicksand">
        <div class="max-w-4xl mx-auto">
            <form action="<?php echo WEB_ROOT; ?>/task/edit" method="POST" class="bg-white rounded-lg shadow-lg p-6">
                <input type="hidden" name="id" value="<?php echo $this->taskEdit['id']; ?>">
                <div class="space-y-4">
                        <h2 class="text-2xl text-gray-700 text-center">Edit Task</h2>
                    <div>
                        <label for="name" class="block text-sm font-medium text-gray-700">Task:</label>
                        <input type="text" id="name" name="name" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3" value="<?php echo $this->taskEdit['name']; ?>">
                    </div>
                    <div>
                        <label for="description" class="block text-sm font-medium text-gray-700">Description:</label>
                        <textarea id="description" name="description" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3"><?php echo $this->taskEdit['description']; ?></textarea>
                    </div>
                    <div>
                        <label for="startDate" class="block text-sm font-medium text-gray-700">Start Date:</label>
                        <input type="date" id="startDate" name="startDate" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3" value="<?php echo $this->taskEdit['startDate']; ?>">
                    </div>
                    <div>
                        <label for="endDate" class="block text-sm font-medium text-gray-700">End Date:</label>
                        <input type="date" id="endDate" name="endDate" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3" value="<?php echo $this->taskEdit['endDate']; ?>">
                    </div>
                    <div>
                        <label for="rank" class="block text-sm font-medium text-gray-700">Status:</label>
                        <select name="rank" id="rank" class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3 focus:outline-none focus:ring-blue-500 focus:border-blue-500" required>
                            <option value="">Choose your option</option>
                            <option value="pending" <?php echo ($this->taskEdit['rank'] == 'pending') ? 'selected' : ''; ?>>Pending</option>
                            <option value="Work in progress" <?php echo ($this->taskEdit['rank'] == 'Work in progress') ? 'selected' : ''; ?>>Work in progress</option>
                            <option value="completed" <?php echo ($this->taskEdit['rank'] == 'completed') ? 'selected' : ''; ?>>Completed</option>
                        </select>
                    </div>
                    <div class="text-center pt-3">
                        <button type="submit" class="bg-blue-500 text-white rounded-md py-2 px-4 inline-block hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Save Changes</button>
                    </div>
                </div>
            </form>
            <form action="<?php echo WEB_ROOT; ?>/task/delete/<?php echo $this->taskEdit['id']; ?>" method="POST" onsubmit="return confirm('Do you want to delete this task?');" class = "text-center pt-2">      
                <button type="submit" class="bg-red-500 text-white rounded-md py-2 px-4 inline-block hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">Delete</button>
            </form>
        </div>
    </div>
</section>