<?php 
$tasks = $this->tasks;
?>
<section class="py-26 max-h-0 bg-white">
<div class="flex flex-col items-center justify-center bg-gray-100 py-8">
    <div class="max-w-4xl mx-auto grid gap-6 grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
        <?php if (!empty($tasks)): ?>
            <?php foreach ($tasks as $task): ?>
                <div class="bg-white rounded-lg shadow-lg p-6">
                    <div class="space-y-4">
                        <h2 class="text-2xl text-gray-700 text-center">TASK</h2>
                        <div>
                            <label for="name" class="block text-sm font-medium text-gray-700">Task:</label>
                            <div class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3">
                                <?php echo htmlspecialchars($task['name']); ?> 
                            </div>
                        </div>
                        <div>
                            <label for="description" class="block text-sm font-medium text-gray-700">Description:</label>
                            <div class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3">
                                <?php echo htmlspecialchars($task['description']); ?>
                            </div>
                        </div>
                        <div>
                            <label for="startDate" class="block text-sm font-medium text-gray-700">Start Date:</label>
                            <div class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3">
                                <?php echo htmlspecialchars($task['startDate']); ?>
                            </div>
                        </div>
                        <div>
                            <label for="endDate" class="block text-sm font-medium text-gray-700">End Date:</label>
                            <div class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3">
                                <?php echo htmlspecialchars($task['endDate']); ?>
                            </div>
                        </div>
                        <div>
                            <label for="rank" class="block text-sm font-medium text-gray-700">Status:</label>
                            <div class="mt-1 block w-full border border-gray-300 rounded-md shadow-sm py-2 px-3">
                                <?php echo htmlspecialchars($task['rank']); ?>
                            </div>
                        </div>
                        <div class="text-center">
                            <a href="task/edit/<?php echo $task['id']; ?>" class="bg-green-500 text-white rounded-md py-2 px-4 inline-block hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500">Editar</a>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>
</section>
