<?php $tasks = $this->tasks?>

<section class="pt-20 p-16 bg-gray-100">
    <ul class="bg-white shadow-lg overflow-hidden sm:rounded-md max-w-sm mx-auto mt-16">
        <li>
            <?php if (!empty($tasks)): ?>
            <?php foreach ($tasks as $task): ?>
            <?php $rankClass= '';
                switch($task['rank']){
                    case 'pending';
                        $rankClass = 'text-red-500';
                        break;
                    case'Work in progress';
                        $rankClass = 'text-yellow-500';
                        break;
                    case 'completed';
                        $rankClass = 'text-green-500';
                        break;
                    default:
                        $rankClass = 'text-gray-500';
                }
            ?>
            <div class="px-4 py-5 sm:px-6 border-t border-gray-200 font-quicksand ">
                <div class="flex items-center justify-between">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">📌  <?php echo htmlspecialchars($task['name']); ?></h3>
                </div>
                <div class="mt-4 flex items-center justify-between">
                    <p class="mt-1 max-w-2xl text-sm text-gray-500"><?php echo htmlspecialchars($task['description'])?></p>
                </div>
                <div class="mt-4 flex items-center justify-between">
                    <p class="text-sm leading-6 text-gray-500">🟢 Start Date: <?php echo date('d-m-y', strtotime($task['startDate'])); ?></p>
                    <p class="text-sm leading-6 text-gray-500">🔴 Last day: <?php echo date('d-m-y', strtotime($task['endDate'])); ?></p>
                </div>
                <div class="mt-4 flex items-center justify-between">
                    <p class="text-sm font-medium text-gray-500">Status: <span class="<?php echo $rankClass; ?>"><?php echo htmlspecialchars($task['rank']); ?></span></p>
                    <a href="task/edit/<?php echo $task['id']; ?>" class="font-medium text-red-600 hover:text-red-500">Edit</a>
                </div>
            </div>
            <?php endforeach; ?>
            <?php endif; ?>
        </li>
    </ul>
</section>

