<header>
  <nav class="bg-white dark:bg-gray-900 fixed w-full z-20 top-0 start-0 border-b border-gray-200 dark:border-gray-600">
    <div class="max-w-screen-xl flex items-center justify-between mx-auto p-4">
      <img src="/images/to-do.ico" width="50px" alt="imagen de agenda">
      <span class="self-center text-2xl font-quicksand text-2xl whitespace-nowrap dark:text-white">TO-DO!</span>
      <div class="flex items-center space-x-3 md:space-x-0 rtl:space-x-reverse ml-auto">
        <ul class="flex flex-col p-4 md:p-0 mt-4 font-quicksand border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="/../task" class="block py-2 px-3 text-purple-700 bg-purple-200 rounded hover:bg-gray-100 md:bg-transparent md:text-white-700 md:p-0 md:hover:bg-transparent md:dark:text-white" aria-current="page">Home</a>
          </li>
          <li>
            <a href="/../task/create" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-purple-700 md:p-0 md:dark:hover:text-purple-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Create Tasks</a>
          </li>
          <li>
            <a href="/../task/edit" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-purple-700 md:p-0 md:dark:hover:text-purple-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Manage Tasks</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>