<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO DO LIST</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <link rel="icon" href="/images/to-do.ico">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" rel="stylesheet" />
    <style>
        .font-quicksand {
            font-family: 'Quicksand', sans-serif;
        }
    </style>

</head>

<body>
    <!-- Header -->
    <?php include(ROOT_PATH . '/app/views/layouts/components/header.phtml'); ?>

    <?php echo $this->content(); ?>

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>

    <!-- Footer -->
    <?php include(ROOT_PATH . '/app/views/layouts/components/footer.phtml'); ?>
</body>

</html>