<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO DO LIST</title>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" rel="stylesheet" />
</head>
  <!-- Header -->
  <?php include(ROOT_PATH . '/app/views/layouts/components/header.phtml');?>
<body>
	<?php echo $this->content(); ?>
	<script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
</body>
<!-- FOOTER -->
	<?php include(ROOT_PATH. '/app/views/layouts/components/footer.phtml');?>
</html>

